; db.ini
db_driver=mysql
db_user=joshch9_oddxcom
db_password=F0rb1dd3nW3$t
db_host=localhost
db_port=3306
db_name=joshch9_oddxcom

[db_options]
PDO::MYSQL_ATTR_INIT_COMMAND=set names utf8

[db_attributes]
ATTR_ERRMODE=ERRMODE_EXCEPTION